### PR TITLE
Added firmware loading tool

### LINKED ISSUE #48: Tool to upgrade firmware
Should be able to download and load the latest firmware.

### PR DESCRIPTION
**Pull request by rohbotics**
Fixes #48

### CODE REVIEW

**Comment by mjstn** [comment]
Use of 'python upgrade_firmware.py   results in missing module no matter how I run it in python

ubuntu@ubiquityrobot:~$ rosrun ubiquity_motor probe_robot -f
29
ubuntu@ubiquityrobot:~$
ubuntu@ubiquityrobot:~$ vi upgrade_firmware.py
ubuntu@ubiquityrobot:~$ python upgrade_firmware.py
Traceback (most recent call last):
  File "upgrade_firmware.py", line 2, in <module>
    import requests
ImportError: No module named requests
ubuntu@ubiquityrobot:~$ sudo python ./upgrade_firmware.py
Traceback (most recent call last):
  File "./upgrade_firmware.py", line 2, in <module>
    import requests
ImportError: No module named requests
ubuntu@ubiquityrobot:~$ python3 upgrade_firmware.py
  File "upgrade_firmware.py", line 16
    """
      ^
SyntaxError: Missing parentheses in call to 'print'
ubuntu@ubiquityrobot:~$

**Comment by rohbotics** [comment]
Ah, try running `sudo apt install python-requests`. I will fix this by making it a dependency in the released version.

**Comment by mjstn** [comment]
If we make this available to users on current images we need to tell them to do this install too of course.

If possible we should check if magni-base is active and EXIT at that point.
I say this because a firmware upgrade always has a potential to brick the PSoC so whatever we can do to be checking OURSELVES is more or less 'required'.

As it is now it makes mention about being sure motor-base is stopped but many 'just do it' people may not know what that means and just 'go for it'

Anyway, I exited and stopped magni-base then ran as normal user and it worked and shows up in probe_robot

A single line separated by spaces just after access token is entered should read

Updating firmware now.   Do not power off the robot.  This is expected to take less than  a minute.

**Comment by rohbotics** [comment]
I added it to the rosdep, so when users install from apt they get all the dependencies. 

Also added the print statement you suggested. 

The firmware loading process does exit if magni-base is running, because the loading handshake never completes, but I agree more robust checking is desirable.

**Comment by rohbotics** [comment]
@mjstn I added a check to make sure the serial port is not open.

@jim-v Ignore the travis, it is just borked. I fixed it in the main branch.

**Review by jim-v — APPROVED** [review]
Looks OK, but I would prefer to see blank lines between Python functions.

**Pull request merged**
