### PR TITLE
Publish estop state as a bool

### LINKED ISSUE #60: Publish E-Stop State

### PR DESCRIPTION
**Pull request by rohbotics**
Needs testing

Fixes #60

### CODE REVIEW

**Review by mjstn — APPROVED** [review]
This deals with the current need for a simple and easily consumable topic that shows motor power state.
Ideally a topic with motor_state and then motor_power under it would be extensible for future needs but this will be ok I think so I will approve as it is a deliverable in some form that a customer is demanding.

**Review by mjstn — COMMENTED** [review]
Oh crud.   Notice that motor power active is true if motor power is on.
This means that motor power active is actually the inversion of estop active.
The diagnostic message now does show motor power state properly using an inversion.

**Comment by rohbotics** [comment]
Thanks for catching the inversion problem, fixed.

**Review by jim-v — APPROVED** [review]

**Review by mjstn — APPROVED** [review]
Looks good now.  I have switched to this branch and tested the code here and it follows the actual switch properly in state.

**Pull request merged**
